
genome_version: GRCm38
genome_release: 86
strandedness: none
design: examples/designs/paired_end_2.csv
conda: /camp/stp/babs/working/software/anaconda/envs/rnaseq_pipeline/

# if you want to override the default modules
modules:
 - cutadapt/1.9.1-foss-2016b-Python-2.7.12

